#!/bin/sh
# -*- sh -*-


if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title fastd peers'
        echo 'graph_vlabel Peers'
        echo 'graph_category network'
        echo 'fastd1.label fastd1'
        echo 'fastd2.label fastd2'

        exit 0
fi

echo -n "fastd1.value "
socat /var/run/fastd1.sock  - | json_pp | grep method |wc -l
echo -n "fastd2.value "
socat /var/run/fastd2.sock  - | json_pp | grep method |wc -l
